---
#
# Copyright (c) 2019 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

- hosts: all
  gather_facts: no

  vars:
    upgrade_kubernetes: true

  tasks:
    - name: Fail if kubernetes_version is not defined
      fail: msg="The mandatory parameter kubernetes_version is not defined."
      when: kubernetes_version is not defined

    - import_role:
        name: common/push-docker-images
      become: yes
