---
#
# Copyright (c) 2020 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
- hosts: all
  gather_facts: no

  vars_files:
    - host_vars/upgrade-platform/default.yml

  roles:
    - common/prepare-env
    - upgrade-platform/prepare-env
