---
#
# Copyright (c) 2019 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

platform_path: /opt/platform
platform_conf_path: /etc/platform
backup_in_progress_flag: "{{ platform_conf_path }}/.backup_in_progress"
host_override_backup_file: "{{ inventory_hostname }}_override_backup.yml"
