---
#
# Copyright (c) 2019 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

platform_path: /opt/platform
platform_conf_path: /etc/platform
backup_in_progress_flag: "{{ platform_conf_path }}/.backup_in_progress"
host_override_backup_file: "{{ inventory_hostname }}_override_backup.yml"

# The max size of data in MB under /home directory that will be backed up.
# If the amount of data is over this limit the backup will abort.
max_home_dir_usage: 2000
