---
#
# Copyright (c) 2020 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# ROLE DESCRIPTION:
#   This role is to configure a NetApp storage backend
#

- name: Set backend filename
  set_fact:
    backend_file: "{{ trident_setup_dir }}/backend-{{ backend.backendName }}.yaml"

# We create, use and delete the backend configuration file, all under one task.
# We do it under one task, because this configuration file may contain user
# credential and doing these steps from 3 different tasks add security issues
- block:
  - name: Add NetApp backend
    shell: "{{ item }}"
    args:
      chdir: "{{ trident_setup_dir }}"
    environment:
      KUBECONFIG: "/etc/kubernetes/admin.conf"
    no_log: true
    with_items:
      - echo '{{ backend | to_nice_json }}' > {{ backend_file }}
      - tridentctl -n {{ trident_namespace }} create backend -f {{ backend_file }}
  always:
    - name: Cleanup backend file
      file:
        path: "{{ backend_file }}"
        state: absent
      when: trident_clean_folder
