---
#
# Copyright (c) 2020 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# ROLE DESCRIPTION:
#   This role will unlock the host when required
#
# Unlock controller-0 for subcloud upgrades
# Retry for 5 mins as the first unlock can require a call to update_sriov_config
- name: Unlock host
  shell: source /etc/platform/openrc; system host-unlock controller-0
  retries: 10
  delay: 30
  register: result
  until: result.rc == 0
  when: distributed_cloud_role == 'subcloud'
